version: '3.8'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/html:/usr/share/nginx/html
    ports:
      - "1935:1935"
      - "8080:8080"
      - "7147:7147"
    depends_on:
      - nms
    restart: unless-stopped

  nms:
    build: ./infra/nms
    ports:
      - "1936:1936"
      - "8000:8000"
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    depends_on:
      - nms
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    ports:
      - "3001:3001"
    restart: unless-stopped
